server:
  port: 8080

header-keys:
  rule-key: "X-B3-URL"

request-validation:
  rules:
    - description: "put phone service"
      key: post/v1/provider
      json-schema: jsonSchema/sampleJsonSchema.json
    - description: "transfer mobile service"
      key: "put/v1/provider2"
      json-schema: jsonSchema/sampleJsonSchema2.json
